### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by danielrhodeswarp** [danielrhodeswarp/JS-Robots#1]
Daniel, update this with the "new" version

**Comment by sendsent** [comment]
This sounds like it could be cool. Is there a new version?

**Comment by danielrhodeswarp** [comment]
Hi @sendsent yes there is a "new" version (it's actually many years old!) at https://github.com/danielrhodeswarp/JS-Robots-2
It has HTML5 graphics and sound, feel free to check it out.
Thank you.
